# Generated by Django 5.2.4 on 2026-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_level',
            field=models.IntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], default=100),
        ),
    ]
