# Generated by Django 5.2.4 on 2026-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_admission_student_admission_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_year',
        ),
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_level',
            field=models.CharField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')]),
        ),
    ]
