# Generated by Django 5.2.4 on 2026-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_admission_year_student_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduation_level',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
