# Generated by Django 5.2.4 on 2026-03-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_level_alter_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
    ]
