# Generated by Django 5.2.4 on 2026-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_created_at_alter_student_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission',
            new_name='admission_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='level_duration',
            field=models.CharField(choices=[('100 Level', 'Year 1'), ('200 Level', 'Year 2'), ('300 Level', 'Year 3'), ('400 Level', 'Year 4'), ('500 Level', 'Year 5'), ('600 Level', 'Year 6')], default='100 Level', max_length=9),
        ),
    ]
