# Generated by Django 5.2.4 on 2026-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_admission_student_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='03_xboxseriesx_tech_chassis_mkt_wbrand_16x9_rgb_resized.jpg', upload_to='student_pics'),
        ),
    ]
