# Generated by Django 5.2.4 on 2026-03-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_duration',
            field=models.CharField(choices=[('1 Year', 'Year 1'), ('2 Years', 'Year 2'), ('3 Years', 'Year 3'), ('4 Years', 'Year 4'), ('5 Years', 'Year 5'), ('6 Years', 'Year 6')], default='1 Year', max_length=9),
        ),
    ]
