# Generated by Django 5.2.4 on 2026-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_department_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='03_xboxseriesx_tech_chassis_mkt_wbrand_16x9_rgb_resized.jpg', upload_to='student_pics'),
        ),
    ]
